const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let section=1, answers={}, submitted=false, result=null, started=Date.now(), elapsed=0, chosen='', sources={}, positions={};
const audio=$('audio'), labels=['music room','assembly hall','computer room','cloakroom','Head’s office','gym','reception'];
const clock=()=>{if(!submitted)elapsed=Math.floor((Date.now()-started)/1000);$('timer').textContent=new Date(elapsed*1000).toISOString().slice(11,19)};setInterval(clock,1000);
function count(){const n=Object.values(answers).filter(Boolean).length;$('answered').textContent=`${n} / 40`;$('progress').style.width=`${n/40*100}%`;document.querySelectorAll('[data-jump]').forEach(b=>{b.classList.toggle('filled',!!answers[b.dataset.jump]);if(result)b.classList.add(result.rows[b.dataset.jump-1].status)});}
function options(q,multi=false){return `<div class="choice-block" id="q${q.n}"><h3><span class="qnum">${multi?q.n+'–'+(q.n+1):q.n}</span>${esc(q.prompt)}</h3>${multi?'<p class="instruction">Choose TWO correct answers.</p>':''}${q.options.map((t,i)=>{const l=String.fromCharCode(65+i);const checked=multi?[answers[q.n],answers[q.n+1]].includes(l):answers[q.n]===l;return `<label class="choice"><input type="${multi?'checkbox':'radio'}" name="q${q.n}" data-choice="${q.n}" data-multi="${multi}" value="${l}" ${checked?'checked':''} ${submitted?'disabled':''}><span class="letter">${l}</span>${esc(t)}</label>`}).join('')}</div>`}
function render(){
 $('sections').innerHTML=[1,2,3,4].map(n=>`<button data-section="${n}" class="${section===n?'active':''}" aria-current="${section===n?'step':'false'}">Section ${n}<small>${n*10-9}–${n*10}</small></button>`).join('');
 let body=TEST.sections[section-1].html;
 if(section===3)body='<p class="subheading">Questions 21–24</p><p class="instruction">Choose the correct answer.</p><h2>Forensic Linguistics</h2>'+TEST.singles.map(q=>options(q)).join('')+TEST.pairs.map(q=>options(q,true)).join('');
 if(section===2)body+=`<div class="map-layout"><div class="map"><img src="Listening%20-%20Vol%209/Test%201/plan.png" alt="Original Spring Down Junior School plan. Question 18 is right of the main entrance, 19 is left of the classrooms, 20 is next to the main hall.">${[18,19,20].map(n=>`<label class="map-slot slot${n}" data-drop="${n}" id="q${n}"><span>${n}</span><select data-q="${n}" aria-label="Câu ${n}" ${submitted?'disabled':''}><option value="">Chọn</option>${labels.map((t,i)=>`<option value="${String.fromCharCode(65+i)}">${String.fromCharCode(65+i)}</option>`).join('')}</select></label>`).join('')}</div><div class="bank"><p>Kéo đáp án vào ô trên sơ đồ, hoặc chọn chữ cái.</p>${labels.map((t,i)=>`<button class="token" draggable="${!submitted}" data-token="${String.fromCharCode(65+i)}" ${submitted?'disabled':''}><b>${String.fromCharCode(65+i)}</b> ${esc(t)}</button>`).join('')}</div></div>`;
 $('paper').innerHTML=`<div class="paper-heading"><h2>Section ${section}</h2><span>${section===3?'Chọn đáp án':section===2?'Điền từ & sơ đồ':'Điền từ'}</span></div>${body}`;
 document.querySelectorAll('[data-q]').forEach(el=>{el.value=answers[el.dataset.q]||'';el.disabled=submitted;el.id=el.id||`q${el.dataset.q}`;el.addEventListener('input',()=>{answers[el.dataset.q]=el.value;count()})});
 document.querySelectorAll('[data-choice]').forEach(el=>el.addEventListener('change',()=>{const n=+el.dataset.choice;if(el.dataset.multi==='true'){const values=[...document.querySelectorAll(`[data-choice="${n}"]:checked`)].map(x=>x.value);if(values.length>2){el.checked=false;return}answers[n]=values[0]||'';answers[n+1]=values[1]||''}else answers[n]=el.value;count()}));
 document.querySelectorAll('[data-token]').forEach(el=>{el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',el.dataset.token));el.addEventListener('click',()=>{chosen=el.dataset.token;document.querySelectorAll('[data-token]').forEach(x=>x.classList.toggle('selected',x===el))})});
 document.querySelectorAll('[data-drop]').forEach(el=>{el.addEventListener('dragover',e=>{if(!submitted)e.preventDefault()});const set=v=>{if(submitted||!/[A-G]/.test(v)||v.length!==1)return;answers[el.dataset.drop]=v;el.querySelector('select').value=v;count()};el.addEventListener('drop',e=>{e.preventDefault();set(e.dataTransfer.getData('text/plain'))});el.addEventListener('click',e=>{if(e.target.tagName!=='SELECT'&&chosen)set(chosen)})});
 $('questions').innerHTML=Array.from({length:40},(_,i)=>`<button data-jump="${i+1}" aria-label="Câu ${i+1}" class="${Math.ceil((i+1)/10)===section?'current-section':''}">${i+1}</button>`).join('');count();
 $('audio-title').textContent=`Audio · Section ${section}`;$('submit').disabled=submitted;
 if(result)document.querySelectorAll('[data-q]').forEach(el=>el.classList.add(result.rows[el.dataset.q-1].status));
}
function change(n){positions[section]=audio.currentTime;audio.pause();section=n;render();loadAudio();}
function loadAudio(){if(sources[section]){audio.src=sources[section];audio.onloadedmetadata=()=>{audio.currentTime=positions[section]||0;audio.playbackRate=+$('speed').value};$('audio-status').textContent=`Đã chọn audio cho Section ${section}.`}else {audio.removeAttribute('src');audio.load();$('audio-status').textContent=`Chưa chọn audio Section ${section}. Chọn file T1-S${section}.mp3 từ máy.`}}
$('sections').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(b)change(+b.dataset.section)});
$('questions').addEventListener('click',e=>{const b=e.target.closest('[data-jump]');if(!b)return;const n=+b.dataset.jump,s=Math.ceil(n/10);if(s!==section)change(s);const id=n>=25&&n<=30?(n%2?n:n-1):n;const el=$('q'+id);el?.scrollIntoView({behavior:'smooth',block:'center'});if(el?.matches('input,select'))el.focus({preventScroll:true})});
$('files').addEventListener('change',e=>{const files=[...e.target.files];let assigned=0;files.forEach(f=>{const match=f.name.match(/(?:T1[-_ ]?)?S([1-4])\b/i);let n=match?+match[1]:files.length===1?section:null;if(!n)return;if(sources[n])URL.revokeObjectURL(sources[n]);sources[n]=URL.createObjectURL(f);assigned++});loadAudio();if(!assigned)$('audio-status').textContent='Chọn từng file để gán cho section hiện tại, hoặc dùng tên T1-S1.mp3 … T1-S4.mp3.'});
$('speed').onchange=()=>audio.playbackRate=+$('speed').value;$('back5').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-5);$('forward5').onclick=()=>{if(Number.isFinite(audio.duration))audio.currentTime=Math.min(audio.duration,audio.currentTime+5)};
audio.onerror=()=>$('audio-status').textContent='Không phát được file này. Hãy chọn lại file MP3 cho section hiện tại.';
$('submit').onclick=()=>{$('confirm-text').textContent=`Bạn đã trả lời ${Object.values(answers).filter(Boolean).length}/40 câu. Nộp bài để xem đúng, sai và đáp án.`;$('confirm').showModal()};$('cancel').onclick=()=>$('confirm').close();
$('finish').onclick=()=>{$('confirm').close();clock();submitted=true;audio.pause();result=EchoGrade.grade(answers,TEST.answers);render();$('results').hidden=false;$('results').innerHTML=`<div class="result-heading"><div><div class="eyebrow">KẾT QUẢ LÀM BÀI</div><h2>${result.correct}<span> / 40 câu đúng</span></h2></div><p>Thời gian: ${esc($('timer').textContent)}</p></div><div class="stats"><div><strong>${result.correct}</strong>Đúng</div><div><strong>${result.wrong}</strong>Sai</div><div><strong>${result.blank}</strong>Bỏ qua</div></div><div class="actions"><button id="review">Xem lại câu hỏi</button><button id="restart">Làm lại</button></div><div class="table-scroll"><table><thead><tr><th>Câu</th><th>Bạn trả lời</th><th>Đáp án</th><th>Kết quả</th></tr></thead><tbody>${result.rows.map(r=>`<tr class="${r.status}"><td>${r.n}</td><td>${esc(r.value)||'—'}</td><td>${esc(r.expected)}</td><td>${r.status==='correct'?'Đúng':r.status==='wrong'?'Sai':'Bỏ qua'}</td></tr>`).join('')}</tbody></table></div>`;$('review').onclick=()=>$('paper').scrollIntoView({behavior:'smooth'});$('restart').onclick=()=>$('restart-dialog').showModal();$('results').scrollIntoView({behavior:'smooth'})};
$('restart-cancel').onclick=()=>$('restart-dialog').close();$('restart-confirm').onclick=()=>{$('restart-dialog').close();answers={};result=null;submitted=false;started=Date.now();elapsed=0;positions={};$('results').hidden=true;change(1);clock();window.scrollTo({top:0,behavior:'smooth'})};
render();clock();
