import assert from 'node:assert/strict';import {mkdtemp,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';
const dir=await mkdtemp(path.join(os.tmpdir(),'echoprep-browser-shared-'));
const server=spawn(process.execPath,['server/server.mjs'],{env:{...process.env,PORT:'8082',ECHOPREP_DATA_DIR:dir},stdio:['ignore','pipe','ignore']});await new Promise((r,j)=>{server.stdout.once('data',r);server.once('exit',()=>j(Error('Server did not start')))});
const chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless','--disable-gpu','--no-first-run','--remote-debugging-port=9224','--user-data-dir='+path.join(dir,'browser')],{stdio:'ignore'});
let ws;try{
 for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:9224/json/version');break}catch{await new Promise(r=>setTimeout(r,100))}}
 const target=await (await fetch('http://127.0.0.1:9224/json/new?http://127.0.0.1:8082/',{method:'PUT'})).json();ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let sequence=0;const pending=new Map();ws.addEventListener('message',event=>{const msg=JSON.parse(event.data);if(msg.id){const p=pending.get(msg.id);if(p){pending.delete(msg.id);msg.error?p.reject(Error(msg.error.message)):p.resolve(msg.result)}}});
 const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
 const wait=async expression=>{for(let i=0;i<80;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+expression)};
 await wait("!!document.getElementById('begin-attempt') && historyStore.status().configured && !historyStore.status().busy");assert.equal(await evaluate("!!document.getElementById('login')"),false);

 let colors=await evaluate("[...document.querySelectorAll('aside [data-start-test]')].map(x=>getComputedStyle(x).backgroundColor)");assert.notEqual(colors[0],colors[1]);assert.equal(colors[1],'rgb(255, 255, 255)');
 await evaluate('startTest(2)');assert.equal(await evaluate('attemptStarted'),false);assert.equal(await evaluate('elapsed'),0);await evaluate("started=Date.now()-60000;clock()");assert.equal(await evaluate('elapsed'),0);await evaluate("$('begin-attempt').click()");assert.equal(await evaluate('attemptStarted'),true);
 await evaluate(`(()=>{const paragraph=document.querySelector('#paper p:has([data-q="1"])');const node=[...paragraph.childNodes].find(n=>n.nodeType===3&&n.textContent.trim().length>8);const range=document.createRange();range.setStart(node,0);range.setEnd(node,8);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);$('paper').dispatchEvent(new MouseEvent('mouseup'));})()`);
 assert.ok(await evaluate("document.querySelectorAll('mark.keyword-highlight').length>0"));await evaluate('change(2);change(1)');assert.ok(await evaluate("document.querySelectorAll('mark.keyword-highlight').length>0"));
 await evaluate(`(()=>{const paragraph=[...document.querySelectorAll('#paper p')].find(p=>p.textContent.includes('Write ONE WORD ONLY'));const range=document.createRange();range.selectNodeContents(paragraph);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);$('paper').dispatchEvent(new MouseEvent('mouseup'));})()`);assert.ok(await evaluate("document.querySelectorAll('mark.keyword-highlight').length>1"));colors=await evaluate("[...document.querySelectorAll('aside [data-start-test]')].map(x=>getComputedStyle(x).backgroundColor)");assert.equal(colors[0],'rgb(255, 255, 255)');assert.notEqual(colors[0],colors[1]);
 await evaluate("(async()=>{answers=Object.fromEntries(Object.entries(TEST.answers).map(([n,v])=>[n,v[0]]));await $('finish').onclick();})()");assert.equal(await evaluate('result.correct'),40);assert.equal(await evaluate('getHistory().length'),1);assert.equal(await evaluate("(async()=> (await (await fetch('/api/history')).json()).length)()"),1);
 await call('Page.reload');await wait("!!document.getElementById('begin-attempt') && !historyStore.status().busy && getHistory().length===1");assert.equal(await evaluate('getHistory().length'),1);await evaluate('showHistory()');assert.equal(await evaluate("document.querySelectorAll('.history-table tbody tr').length"),1);
 await evaluate("document.querySelector('[data-history-view]').click()");assert.ok(await evaluate("document.querySelectorAll('mark.keyword-highlight').length>1"));assert.ok(await evaluate('!!getHistory()[0].highlights[1]'));
 await evaluate("$('restart-confirm').click();$('begin-attempt').click()");assert.equal(await evaluate("document.querySelectorAll('mark.keyword-highlight').length"),0);assert.equal(await evaluate('Object.keys(highlights).length'),0);
 await evaluate("answers={1:'month'};(async()=>{await $('finish').onclick()})()");assert.equal(await evaluate('getHistory().length'),2);assert.equal(await evaluate('Object.keys(getHistory()[1].highlights).length'),0);assert.ok(await evaluate('!!getHistory()[0].highlights[1]'));
 await evaluate("startTest({module:'reading',id:1})");assert.equal(await evaluate('attemptStarted'),false);assert.equal(await evaluate("$('transcript-pane').hidden"),true);
 await evaluate("$('begin-attempt').click();started=Date.now()-7200000;clock()");assert.equal(await evaluate("$('timer').textContent"),'02:00:00');assert.equal(await evaluate('submitted'),false);
 await evaluate(`document.querySelector('[data-choice="1"][value="FALSE"]').click();document.querySelector('[data-choice="2"][value="NOT GIVEN"]').click();$('q7').value='water';$('q7').dispatchEvent(new Event('input'));change(2);$('heading14').value='vii';$('heading14').dispatchEvent(new Event('input'));`);assert.equal(await evaluate("$('q14').value"),'vii');
 await evaluate(`document.querySelector('[data-choice="21"][value="A"]').click();document.querySelector('[data-choice="21"][value="C"]').click();change(3);$('q27').value='B';$('q27').dispatchEvent(new Event('input'));change(1)`);
 assert.equal(await evaluate(`document.querySelector('[data-choice="1"]:checked').value`),'FALSE');assert.equal(await evaluate("$('q7').value"),'water');await evaluate('change(2)');assert.equal(await evaluate("$('heading14').value"),'vii');assert.equal(await evaluate(`document.querySelectorAll('[data-choice="21"]:checked').length`),2);
 await evaluate(`(()=>{const p=document.querySelector('#transcript-body p');const range=document.createRange();range.selectNodeContents(p);getSelection().removeAllRanges();getSelection().addRange(range);$('transcript-body').dispatchEvent(new MouseEvent('mouseup'))})()`);assert.ok(await evaluate("document.querySelectorAll('#transcript-body mark.keyword-highlight').length>0"));await evaluate('change(3);change(2)');assert.ok(await evaluate("document.querySelectorAll('#transcript-body mark.keyword-highlight').length>0"));
 await evaluate("(async()=>{await $('finish').onclick()})()");assert.equal(await evaluate('result.correct'),7);assert.equal(await evaluate('getHistory().at(-1).module'),'reading');assert.ok(await evaluate("Object.keys(getHistory().at(-1).highlights['passage:2']).length>0"));await evaluate('showExplanation(14)');if(process.env.ECHOPREP_SCREENSHOT){await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await writeFile('/tmp/echoprep-reading.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));}assert.equal(await evaluate('section'),2);assert.equal(await evaluate("$('explanation-sheet').hidden"),false);assert.ok(await evaluate("document.querySelector('.evidence-active')?.id===TEST.questionSegments[14][0]"));
 await evaluate('showHistory()');assert.equal(await evaluate("document.querySelectorAll('.history-table tbody tr').length"),1);await evaluate("document.querySelector('[data-history-view]').click();change(2)");assert.ok(await evaluate("document.querySelectorAll('#transcript-body mark.keyword-highlight').length>0"));
 await evaluate("$('restart-confirm').click();$('time-mode').value='timed';$('begin-attempt').click();started=Date.now()-90000;clock()");assert.equal(await evaluate("$('timer').textContent"),'00:58:30');assert.equal(await evaluate("document.querySelectorAll('mark.keyword-highlight').length"),0);assert.equal(await evaluate('Object.keys(answers).length'),0);
 await evaluate("$('abort-attempt').click();$('abort-confirm').click()");assert.equal(await evaluate("getHistory().filter(r=>r.module==='reading').length"),1);
 console.log('PASS READING: start gate, unlimited two-hour count-up, timed countdown, answers across all passages, synchronized headings, pair choices, passage highlights, grading, per-module history, review evidence/bottom sheet, clean retry and cancellation.');
 // A new Chrome target has no login/session and can still read the same saved history.
 const second=await (await fetch('http://127.0.0.1:9224/json/new?http://127.0.0.1:8082/',{method:'PUT'})).json();
 const socket=new WebSocket(second.webSocketDebuggerUrl);await new Promise(r=>socket.addEventListener('open',r,{once:true}));
 const secondRows=await new Promise((resolve,reject)=>{socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id===1){socket.close();m.result?.exceptionDetails?reject(Error('Second client failed')):resolve(m.result?.result?.value)}});socket.send(JSON.stringify({id:1,method:'Runtime.evaluate',params:{expression:"fetch('/api/history').then(r=>r.json()).then(rows=>rows.length)",awaitPromise:true,returnByValue:true}}));});assert.equal(secondRows,3);
 console.log('PASS BROWSER: no login, shared history readable from another client, distinct test colors, separate submissions, saved highlights after reload, retry/reset, and all Reading interactions.');

}finally{ws?.close();chrome.kill('SIGTERM');server.kill('SIGTERM');}
