import assert from 'node:assert/strict';import {mkdtemp,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {scrypt,randomBytes} from 'node:crypto';import {promisify} from 'node:util';import {spawn} from 'node:child_process';
const dir=await mkdtemp(path.join(os.tmpdir(),'echoprep-browser-auth-')),salt=randomBytes(16).toString('hex');await writeFile(path.join(dir,'accounts.json'),JSON.stringify([{username:'qa_user',salt,hash:(await promisify(scrypt)('qa_password',salt,64)).toString('hex')}]),{mode:0o600});
const server=spawn(process.execPath,['server/server.mjs'],{env:{...process.env,PORT:'8082',ECHOPREP_DATA_DIR:dir},stdio:['ignore','pipe','ignore']});await new Promise((r,j)=>{server.stdout.once('data',r);server.once('exit',()=>j(Error('Server did not start')))});
const chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless','--disable-gpu','--no-first-run','--remote-debugging-port=9224','--user-data-dir='+path.join(dir,'browser')],{stdio:'ignore'});
let ws;try{
 for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:9224/json/version');break}catch{await new Promise(r=>setTimeout(r,100))}}
 const target=await (await fetch('http://127.0.0.1:9224/json/new?http://127.0.0.1:8082/login',{method:'PUT'})).json();ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let sequence=0;const pending=new Map();ws.addEventListener('message',event=>{const msg=JSON.parse(event.data);if(msg.id){const p=pending.get(msg.id);if(p){pending.delete(msg.id);msg.error?p.reject(Error(msg.error.message)):p.resolve(msg.result)}}});
 const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
 const wait=async expression=>{for(let i=0;i<80;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+expression)};
 await wait("!!document.getElementById('username')");await evaluate("document.getElementById('username').value='qa_user';document.getElementById('password').value='wrong';document.getElementById('login').requestSubmit()");await wait("document.getElementById('error')?.textContent.includes('không đúng')");
 await evaluate("document.getElementById('password').value='qa_password';document.getElementById('login').requestSubmit()");await wait("document.querySelector('.account-user')?.textContent==='qa_user'");
 let colors=await evaluate("[...document.querySelectorAll('aside [data-start-test]')].map(x=>getComputedStyle(x).backgroundColor)");assert.notEqual(colors[0],colors[1]);assert.equal(colors[1],'rgb(255, 255, 255)');
 await evaluate('startTest(2)');colors=await evaluate("[...document.querySelectorAll('aside [data-start-test]')].map(x=>getComputedStyle(x).backgroundColor)");assert.equal(colors[0],'rgb(255, 255, 255)');assert.notEqual(colors[0],colors[1]);
 await evaluate("(async()=>{answers=Object.fromEntries(Object.entries(TEST.answers).map(([n,v])=>[n,v[0]]));await $('finish').onclick();})()");assert.equal(await evaluate('result.correct'),40);assert.equal(await evaluate('getHistory().length'),1);assert.equal(await evaluate("(async()=> (await accountAPI('/api/history')).length)()"),1);
 await call('Page.reload');await wait("document.querySelector('.account-user')?.textContent==='qa_user'");assert.equal(await evaluate('getHistory().length'),1);await evaluate('showHistory()');assert.equal(await evaluate("document.querySelectorAll('.history-table tbody tr').length"),1);
 await evaluate("(async()=>{await accountAPI('/api/logout',{method:'POST'});location.reload()})()");await wait("!!document.getElementById('login')");assert.equal(await evaluate("!!document.getElementById('paper')"),false);
 console.log('PASS BROWSER: incorrect/correct login, distinct Test1/Test2 colors, server-saved submission, history after reload and protected logout.');
}finally{ws?.close();chrome.kill('SIGTERM');server.kill('SIGTERM');}
